//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.10 at 10:04:12 PM IST 
//


package com.avaya.grt.jms.fmw.xml.equipmentRemoval.jms;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EquipmentRemovalRespDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EquipmentRemovalRespDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ShipTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EquipmentNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Action" type="{http://avaya.com/v1/equipmentremoval}ActionType"/>
 *         &lt;element name="InitialQuantity" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="FinalQuantity" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="ErrorDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EquipmentRemovalRespDataType", propOrder = {
    "shipTo",
    "equipmentNumber",
    "action",
    "initialQuantity",
    "finalQuantity",
    "errorDescription",
    "beforeQuantity",
    "afterQuantity"
})
public class EquipmentRemovalRespDataType {

    @XmlElement(name = "ShipTo", required = true)
    protected String shipTo;
    @XmlElement(name = "EquipmentNumber", required = true)
    protected String equipmentNumber;
    @XmlElement(name = "Action", required = true)
    protected ActionType action;
    @XmlElement(name = "InitialQuantity", required = true)
    protected BigInteger initialQuantity;
    @XmlElement(name = "FinalQuantity", required = true)
    protected BigInteger finalQuantity;
    @XmlElement(name = "ErrorDescription")
    protected String errorDescription;
    @XmlElement(name = "BeforeQuantity")
    protected String beforeQuantity;
    @XmlElement(name = "AfterQuantity")
    protected String afterQuantity;
    
    /**
     * Gets the value of the shipTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipTo() {
        return shipTo;
    }

    /**
     * Sets the value of the shipTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipTo(String value) {
        this.shipTo = value;
    }

    /**
     * Gets the value of the equipmentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipmentNumber() {
        return equipmentNumber;
    }

    /**
     * Sets the value of the equipmentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipmentNumber(String value) {
        this.equipmentNumber = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the initialQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInitialQuantity() {
        return initialQuantity;
    }

    /**
     * Sets the value of the initialQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInitialQuantity(BigInteger value) {
        this.initialQuantity = value;
    }

    /**
     * Gets the value of the finalQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFinalQuantity() {
        return finalQuantity;
    }

    /**
     * Sets the value of the finalQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFinalQuantity(BigInteger value) {
        this.finalQuantity = value;
    }

    /**
     * Gets the value of the errorDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorDescription() {
        return errorDescription;
    }

    /**
     * Sets the value of the errorDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorDescription(String value) {
        this.errorDescription = value;
    }

	public String getBeforeQuantity() {
		return beforeQuantity;
	}

	public void setBeforeQuantity(String beforeQuantity) {
		this.beforeQuantity = beforeQuantity;
	}

	public String getAfterQuantity() {
		return afterQuantity;
	}

	public void setAfterQuantity(String afterQuantity) {
		this.afterQuantity = afterQuantity;
	}

}
