//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.10 at 10:04:12 PM IST 
//


package com.avaya.grt.jms.fmw.xml.equipmentMove.jms;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EquipmentRemovalRespDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EquipmentRemovalRespDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ShipTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EquipmentNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Action" type="{http://avaya.com/v1/equipmentremoval}ActionType"/>
 *         &lt;element name="InitialQuantity" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="FinalQuantity" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="ErrorDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EquipmentMoveRespDataType", propOrder = {
    "fromequipmentNumber",
    "fromBeforeQuantity",
    "fromAfterQuantity",
    "movedQuantity",
    "toequipmentNumber",
    "toBeforeQuantity",
    "toAfterQuantity",
    "returnCode",
    "errorDesc"
})
public class EquipmentMoveRespDataType {
    
    @XmlElement(name = "FromEquipmentNumber", required = true, namespace = "http://avaya.com/v4/equipmentmove")
    protected String fromequipmentNumber;
    @XmlElement(name = "FromBeforeQuantity", required = true, namespace = "http://avaya.com/v4/equipmentmove")
    protected BigDecimal fromBeforeQuantity;
    @XmlElement(name = "FromAfterQuantity", required = true, namespace = "http://avaya.com/v4/equipmentmove")
    protected BigDecimal fromAfterQuantity;
    @XmlElement(name = "MovedQuantity", required = true, namespace = "http://avaya.com/v4/equipmentmove")
    protected BigDecimal movedQuantity;
    @XmlElement(name = "ToEquipmentNumber", required = true, namespace = "http://avaya.com/v4/equipmentmove")
    protected String toequipmentNumber;
    @XmlElement(name = "ToBeforeQuantity", required = true, namespace = "http://avaya.com/v4/equipmentmove")
    protected BigDecimal toBeforeQuantity;
    @XmlElement(name = "ToAfterQuantity", required = true, namespace = "http://avaya.com/v4/equipmentmove")
    protected BigDecimal toAfterQuantity;
    @XmlElement(name = "ReturnCode", required = true, namespace = "http://avaya.com/v4/equipmentmove")
    protected String returnCode;
    @XmlElement(name = "ErrorDesc", required = true, namespace = "http://avaya.com/v4/equipmentmove")
    protected String errorDesc;
    
	public String getFromequipmentNumber() {
		return fromequipmentNumber;
	}
	
	public void setFromequipmentNumber(String fromequipmentNumber) {
		this.fromequipmentNumber = fromequipmentNumber;
	}
	
	public BigDecimal getFromBeforeQuantity() {
		return fromBeforeQuantity;
	}
	
	public void setFromBeforeQuantity(BigDecimal fromBeforeQuantity) {
		this.fromBeforeQuantity = fromBeforeQuantity;
	}
	
	public BigDecimal getFromAfterQuantity() {
		return fromAfterQuantity;
	}
	
	public void setFromAfterQuantity(BigDecimal fromAfterQuantity) {
		this.fromAfterQuantity = fromAfterQuantity;
	}
	
	public BigDecimal getMovedQuantity() {
		return movedQuantity;
	}
	
	public void setMovedQuantity(BigDecimal movedQuantity) {
		this.movedQuantity = movedQuantity;
	}
	
	public String getToequipmentNumber() {
		return toequipmentNumber;
	}
	
	public void setToequipmentNumber(String toequipmentNumber) {
		this.toequipmentNumber = toequipmentNumber;
	}
	
	public BigDecimal getToBeforeQuantity() {
		return toBeforeQuantity;
	}
	
	public void setToBeforeQuantity(BigDecimal toBeforeQuantity) {
		this.toBeforeQuantity = toBeforeQuantity;
	}
	
	public BigDecimal getToAfterQuantity() {
		return toAfterQuantity;
	}
	
	public void setToAfterQuantity(BigDecimal toAfterQuantity) {
		this.toAfterQuantity = toAfterQuantity;
	}
	
	public String getReturnCode() {
		return returnCode;
	}
	
	public void setReturnCode(String returnCode) {
		this.returnCode = returnCode;
	}
	
	public String getErrorDesc() {
		return errorDesc;
	}
	
	public void setErrorDesc(String errorDesc) {
		this.errorDesc = errorDesc;
	}
    
    
}
