//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.27 at 11:51:31 AM EDT 
//


package com.avaya.grt.jms.fmw.xml.filePoller.jms;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.avaya.grt.jms.fmw.xml.filePoller.jms.HeaderType;
import com.avaya.grt.jms.fmw.xml.filePoller.jms.IBaseCreateRequestType;
import com.avaya.grt.jms.fmw.xml.filePoller.jms.IBaseDataType;


/**
 * <p>Java class for iBaseCreateRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="iBaseCreateRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header" type="{http://avaya.com/v1/installbase}headerType"/>
 *         &lt;element name="iBaseData" type="{http://avaya.com/v1/installbase}iBaseDataType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "iBaseCreateRequestType", propOrder = {
    "header",
    "iBaseData"
})
public class IBaseCreateRequestType {

    @XmlElement(namespace = "http://avaya.com/v1/installbase")
    protected HeaderType header;
    @XmlElement(namespace = "http://avaya.com/v1/installbase")
    protected List<IBaseDataType> iBaseData;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderType }
     *     
     */
    public HeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderType }
     *     
     */
    public void setHeader(HeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the iBaseData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the iBaseData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIBaseData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IBaseDataType }
     * 
     * 
     */
    public List<IBaseDataType> getIBaseData() {
        if (iBaseData == null) {
            iBaseData = new ArrayList<IBaseDataType>();
        }
        return this.iBaseData;
    }

}
