//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2012.03.26 at 04:14:18 PM EDT 
//


package com.avaya.grt.service.iposs;

import javax.xml.bind.annotation.XmlRegistry;
import com.avaya.grt.service.iposs.HeaderType;
import com.avaya.grt.service.iposs.ObjectFactory;
import com.avaya.grt.service.iposs.Response;
import com.avaya.grt.service.iposs.Response.Data;
import com.avaya.grt.service.iposs.Response.Data.Inventory;
import com.avaya.grt.service.iposs.Response.Data.Inventory.Hardware;
import com.avaya.grt.service.iposs.Response.Data.Inventory.Hardware.Modules;
import com.avaya.grt.service.iposs.Response.Data.Inventory.Hardware.Modules.Module;
import com.avaya.grt.service.iposs.Response.Data.Inventory.Hardware.SDCard;
import com.avaya.grt.service.iposs.Response.Data.Inventory.Hardware.Units;
import com.avaya.grt.service.iposs.Response.Data.Inventory.Hardware.Units.Unit;
import com.avaya.grt.service.iposs.Response.Data.Inventory.Licenses;
import com.avaya.grt.service.iposs.Response.Data.Inventory.Licenses.License;
import com.avaya.grt.service.iposs.Response.Data.Inventory.Software;
import com.avaya.grt.service.iposs.Response.Data.Inventory.Software.Component;


/**
* This object contains factory methods for each 
* Java content interface and Java element interface 
* generated in the jaxbClasses package. 
* <p>An ObjectFactory allows you to programatically 
* construct new instances of the Java representation 
* for XML content. The Java representation of XML 
* content can consist of schema derived interfaces 
* and classes representing the binding of schema 
* type definitions, element declarations and model 
* groups.  Factory methods for each of these are 
* provided in this class.
* 
*/
@XmlRegistry
public class ObjectFactory {


 /**
  * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxbClasses
  * 
  */
 public ObjectFactory() {
 }

 /**
  * Create an instance of {@link Data }
  * 
  */
 public Data createResponseData() {
     return new Data();
 }

 /**
  * Create an instance of {@link HeaderType }
  * 
  */
 public HeaderType createHeaderType() {
     return new HeaderType();
 }

 /**
  * Create an instance of {@link Software }
  * 
  */
 public Software createResponseDataInventorySoftware() {
     return new Software();
 }

 /**
  * Create an instance of {@link Component }
  * 
  */
 public Component createResponseDataInventorySoftwareComponent() {
     return new Component();
 }

 /**
  * Create an instance of {@link Response }
  * 
  */
 public Response createResponse() {
     return new Response();
 }

 /**
  * Create an instance of {@link Unit }
  * 
  */
 public Unit createResponseDataInventoryHardwareUnitsUnit() {
     return new Unit();
 }

 /**
  * Create an instance of {@link Licenses }
  * 
  */
 public Licenses createResponseDataInventoryLicenses() {
     return new Licenses();
 }

 /**
  * Create an instance of {@link Modules }
  * 
  */
 public Modules createResponseDataInventoryHardwareModules() {
     return new Modules();
 }

 /**
  * Create an instance of {@link Hardware }
  * 
  */
 public Hardware createResponseDataInventoryHardware() {
     return new Hardware();
 }

 /**
  * Create an instance of {@link Units }
  * 
  */
 public Units createResponseDataInventoryHardwareUnits() {
     return new Units();
 }

 /**
  * Create an instance of {@link Module }
  * 
  */
 public Module createResponseDataInventoryHardwareModulesModule() {
     return new Module();
 }

 /**
  * Create an instance of {@link License }
  * 
  */
 public License createResponseDataInventoryLicensesLicense() {
     return new License();
 }

 /**
  * Create an instance of {@link SDCard }
  * 
  */
 public SDCard createResponseDataInventoryHardwareSDCard() {
     return new SDCard();
 }

 /**
  * Create an instance of {@link Inventory }
  * 
  */
 public Inventory createResponseDataInventory() {
     return new Inventory();
 }

}

