//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.27 at 11:51:48 AM EDT 
//


package com.avaya.grt.jms.siebel.xml.assetupdate.jms;

import javax.xml.bind.annotation.XmlRegistry;


import com.avaya.grt.jms.siebel.xml.assetupdate.jms.ObjectFactory;
import com.avaya.grt.jms.siebel.xml.assetupdate.jms.SiebelMessage;
import com.avaya.grt.jms.siebel.xml.assetupdate.jms.SiebelMessage.ListOfAvayaGrtRegistration;
import com.avaya.grt.jms.siebel.xml.assetupdate.jms.SiebelMessage.ListOfAvayaGrtRegistration.AvayaGrtRegistration;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the siebelAssetUpdate package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: siebelAssetUpdate
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListOfAvayaGrtRegistration }
     * 
     */
    public ListOfAvayaGrtRegistration createSiebelMessageListOfAvayaGrtRegistration() {
        return new ListOfAvayaGrtRegistration();
    }

    /**
     * Create an instance of {@link AvayaGrtRegistration }
     * 
     */
    public AvayaGrtRegistration createSiebelMessageListOfAvayaGrtRegistrationAvayaGrtRegistration() {
        return new AvayaGrtRegistration();
    }

    /**
     * Create an instance of {@link SiebelMessage }
     * 
     */
    public SiebelMessage createSiebelMessage() {
        return new SiebelMessage();
    }

}
