//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.27 at 11:51:31 AM EDT 
//


package com.avaya.grt.jms.fmw.xml.filePoller.jms;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.avaya.grt.jms.fmw.xml.filePoller.jms.IBaseCreateRespType;
import com.avaya.grt.jms.fmw.xml.filePoller.jms.IBaseRespDataType;
import com.avaya.grt.jms.fmw.xml.filePoller.jms.RespheaderType;


/**
 * <p>Java class for iBaseCreateRespType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="iBaseCreateRespType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="iBaseheader" type="{http://avaya.com/v1/installbase}RespheaderType"/>
 *         &lt;element name="iBaseRespData" type="{http://avaya.com/v1/installbase}iBaseRespDataType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "iBaseCreateRespType", propOrder = {
    "iBaseheader",
    "iBaseRespData"
})
public class IBaseCreateRespType {

    @XmlElement(namespace = "http://avaya.com/v1/installbase")
    protected RespheaderType iBaseheader;
    @XmlElement(namespace = "http://avaya.com/v1/installbase")
    protected List<IBaseRespDataType> iBaseRespData;

    /**
     * Gets the value of the iBaseheader property.
     * 
     * @return
     *     possible object is
     *     {@link RespheaderType }
     *     
     */
    public RespheaderType getIBaseheader() {
        return iBaseheader;
    }

    /**
     * Sets the value of the iBaseheader property.
     * 
     * @param value
     *     allowed object is
     *     {@link RespheaderType }
     *     
     */
    public void setIBaseheader(RespheaderType value) {
        this.iBaseheader = value;
    }

    /**
     * Gets the value of the iBaseRespData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the iBaseRespData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIBaseRespData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IBaseRespDataType }
     * 
     * 
     */
    public List<IBaseRespDataType> getIBaseRespData() {
        if (iBaseRespData == null) {
            iBaseRespData = new ArrayList<IBaseRespDataType>();
        }
        return this.iBaseRespData;
    }

}
