//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.27 at 11:51:31 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://avaya.com/v1/installbase")
package com.avaya.grt.jms.fmw.xml.filePoller.jms;
