//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.15 at 01:24:55 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.siebel.com/xml/AVAYA%20Service%20Request%20-%20JMS", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.avaya.grt.jms.siebel.xml.service20request_2.jms;
