//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.15 at 01:24:55 PM CST 
//


package com.avaya.grt.jms.siebel.xml.service20request_2.jms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SiebelMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SiebelMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ListOfAvayaServiceRequest-Jms" type="{http://www.siebel.com/xml/AVAYA%20Service%20Request%20-%20JMS}ListOfAvayaServiceRequest-Jms" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="MessageId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MessageType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IntObjectName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IntObjectFormat" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SiebelMessage", propOrder = {
    "listOfAvayaServiceRequestJms"
})
public class SiebelMessage {

    @XmlElement(name = "ListOfAvayaServiceRequest-Jms")
    protected ListOfAvayaServiceRequestJms listOfAvayaServiceRequestJms;
    @XmlAttribute(name = "MessageId")
    protected String messageId;
    @XmlAttribute(name = "MessageType")
    protected String messageType;
    @XmlAttribute(name = "IntObjectName")
    protected String intObjectName;
    @XmlAttribute(name = "IntObjectFormat")
    protected String intObjectFormat;

    /**
     * Gets the value of the listOfAvayaServiceRequestJms property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfAvayaServiceRequestJms }
     *     
     */
    public ListOfAvayaServiceRequestJms getListOfAvayaServiceRequestJms() {
        return listOfAvayaServiceRequestJms;
    }

    /**
     * Sets the value of the listOfAvayaServiceRequestJms property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfAvayaServiceRequestJms }
     *     
     */
    public void setListOfAvayaServiceRequestJms(ListOfAvayaServiceRequestJms value) {
        this.listOfAvayaServiceRequestJms = value;
    }

    /**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageId(String value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the messageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * Sets the value of the messageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageType(String value) {
        this.messageType = value;
    }

    /**
     * Gets the value of the intObjectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntObjectName() {
        return intObjectName;
    }

    /**
     * Sets the value of the intObjectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntObjectName(String value) {
        this.intObjectName = value;
    }

    /**
     * Gets the value of the intObjectFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntObjectFormat() {
        return intObjectFormat;
    }

    /**
     * Sets the value of the intObjectFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntObjectFormat(String value) {
        this.intObjectFormat = value;
    }

}
