//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 11:47:56 AM IST 
//


package com.avaya.grt.jms.avaya.v2.techregistration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for NewSEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NewSEType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NewSEID" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="SeCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="IpAddress" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="AlarmID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="FailedSEID" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="RecordNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="SeCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NewSEType", propOrder = {
    "newSEID",
    "failedSEID"
})
public class NewSEType {

    @XmlElement(name = "NewSEID", required = true)
    protected List<NewSEType.NewSEID> newSEID;
    @XmlElement(name = "FailedSEID")
    protected NewSEType.FailedSEID failedSEID;

    /**
     * Gets the value of the newSEID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the newSEID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNewSEID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NewSEType.NewSEID }
     * 
     * 
     */
    public List<NewSEType.NewSEID> getNewSEID() {
        if (newSEID == null) {
            newSEID = new ArrayList<NewSEType.NewSEID>();
        }
        return this.newSEID;
    }

    /**
     * Gets the value of the failedSEID property.
     * 
     * @return
     *     possible object is
     *     {@link NewSEType.FailedSEID }
     *     
     */
    public NewSEType.FailedSEID getFailedSEID() {
        return failedSEID;
    }

    /**
     * Sets the value of the failedSEID property.
     * 
     * @param value
     *     allowed object is
     *     {@link NewSEType.FailedSEID }
     *     
     */
    public void setFailedSEID(NewSEType.FailedSEID value) {
        this.failedSEID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="RecordNum" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="SeCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class FailedSEID {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "RecordNum")
        protected String recordNum;
        @XmlAttribute(name = "SeCode")
        protected String seCode;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the recordNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordNum() {
            return recordNum;
        }

        /**
         * Sets the value of the recordNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordNum(String value) {
            this.recordNum = value;
        }

        /**
         * Gets the value of the seCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeCode() {
            return seCode;
        }

        /**
         * Sets the value of the seCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeCode(String value) {
            this.seCode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="SeCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="IpAddress" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="AlarmID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class NewSEID {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "SeCode", required = true)
        protected String seCode;
        @XmlAttribute(name = "IpAddress")
        protected String ipAddress;
        @XmlAttribute(name = "AlarmID")
        protected String alarmID;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the seCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeCode() {
            return seCode;
        }

        /**
         * Sets the value of the seCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeCode(String value) {
            this.seCode = value;
        }

        /**
         * Gets the value of the ipAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIpAddress() {
            return ipAddress;
        }

        /**
         * Sets the value of the ipAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIpAddress(String value) {
            this.ipAddress = value;
        }

        /**
         * Gets the value of the alarmID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAlarmID() {
            return alarmID;
        }

        /**
         * Sets the value of the alarmID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAlarmID(String value) {
            this.alarmID = value;
        }

    }

}
