//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.10 at 10:04:12 PM IST 
//


package com.avaya.grt.jms.fmw.xml.equipmentRemoval.jms;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EquipmentRemovalRespType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EquipmentRemovalRespType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{http://avaya.com/v1/equipmentremoval}RespHeaderType"/>
 *         &lt;element name="EquipmentRemovalRespData" type="{http://avaya.com/v1/equipmentremoval}EquipmentRemovalRespDataType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EquipmentRemovalRespType", propOrder = {
    "header",
    "equipmentRemovalRespData"
})
public class EquipmentRemovalRespType {

    @XmlElement(name = "Header", required = true)
    protected RespHeaderType header;
    @XmlElement(name = "EquipmentRemovalRespData", required = true)
    protected List<EquipmentRemovalRespDataType> equipmentRemovalRespData;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link RespHeaderType }
     *     
     */
    public RespHeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link RespHeaderType }
     *     
     */
    public void setHeader(RespHeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the equipmentRemovalRespData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipmentRemovalRespData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEquipmentRemovalRespData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EquipmentRemovalRespDataType }
     * 
     * 
     */
    public List<EquipmentRemovalRespDataType> getEquipmentRemovalRespData() {
        if (equipmentRemovalRespData == null) {
            equipmentRemovalRespData = new ArrayList<EquipmentRemovalRespDataType>();
        }
        return this.equipmentRemovalRespData;
    }

}
