//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.10 at 10:04:12 PM IST 
//


package com.avaya.grt.jms.fmw.xml.equipmentRemoval.jms;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.grt.integration.jms.fmw.xml.equipmentRemoval.jms package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EquipmentRemovalAcknowledgement_QNAME = new QName("http://avaya.com/v1/equipmentremoval", "EquipmentRemovalAcknowledgement");
    private final static QName _EquipmentRemovalRequest_QNAME = new QName("http://avaya.com/v1/equipmentremoval", "EquipmentRemovalRequest");
    private final static QName _EquipmentRemovalResult_QNAME = new QName("http://avaya.com/v1/equipmentremoval", "EquipmentRemovalResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.grt.integration.jms.fmw.xml.equipmentRemoval.jms
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EquipmentRemovalRequestType }
     * 
     */
    public EquipmentRemovalRequestType createEquipmentRemovalRequestType() {
        return new EquipmentRemovalRequestType();
    }

    /**
     * Create an instance of {@link EquipmentRemovalAckType }
     * 
     */
    public EquipmentRemovalAckType createEquipmentRemovalAckType() {
        return new EquipmentRemovalAckType();
    }

    /**
     * Create an instance of {@link EquipmentRemovalRespType }
     * 
     */
    public EquipmentRemovalRespType createEquipmentRemovalRespType() {
        return new EquipmentRemovalRespType();
    }

    /**
     * Create an instance of {@link EquipmentRemovalRespDataType }
     * 
     */
    public EquipmentRemovalRespDataType createEquipmentRemovalRespDataType() {
        return new EquipmentRemovalRespDataType();
    }

    /**
     * Create an instance of {@link RespHeaderType }
     * 
     */
    public RespHeaderType createRespHeaderType() {
        return new RespHeaderType();
    }

    /**
     * Create an instance of {@link EquipmentRemovalDataType }
     * 
     */
    public EquipmentRemovalDataType createEquipmentRemovalDataType() {
        return new EquipmentRemovalDataType();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EquipmentRemovalAckType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://avaya.com/v1/equipmentremoval", name = "EquipmentRemovalAcknowledgement")
    public JAXBElement<EquipmentRemovalAckType> createEquipmentRemovalAcknowledgement(EquipmentRemovalAckType value) {
        return new JAXBElement<EquipmentRemovalAckType>(_EquipmentRemovalAcknowledgement_QNAME, EquipmentRemovalAckType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EquipmentRemovalRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://avaya.com/v1/equipmentremoval", name = "EquipmentRemovalRequest")
    public JAXBElement<EquipmentRemovalRequestType> createEquipmentRemovalRequest(EquipmentRemovalRequestType value) {
        return new JAXBElement<EquipmentRemovalRequestType>(_EquipmentRemovalRequest_QNAME, EquipmentRemovalRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EquipmentRemovalRespType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://avaya.com/v1/equipmentremoval", name = "EquipmentRemovalResult")
    public JAXBElement<EquipmentRemovalRespType> createEquipmentRemovalResult(EquipmentRemovalRespType value) {
        return new JAXBElement<EquipmentRemovalRespType>(_EquipmentRemovalResult_QNAME, EquipmentRemovalRespType.class, null, value);
    }

}
