//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 11:47:56 AM IST 
//


package com.avaya.grt.jms.avaya.v4.techregistration;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.avaya.grt.jms.avaya.v4.techregistration.KeyValueListType;


/**
 * <p>Java class for OutputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OutputType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TechRegId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Sid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Mid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SolutionElements" type="{http://avaya.com/v2/techregistration}NewSEType"/>
 *         &lt;element name="TransactionDetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RegResult" type="{http://avaya.com/v2/techregistration}RegResultType"/>
 *         &lt;element name="InstallScript" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OnBoardingXML" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TechRegAlarmElement", propOrder = {
    "techRegId",
    "onBoardingOp",
    "seid",
    "accessType",
    "activityLog",
    "returnCode",
    "description",
    "keyValueList"    
})
public class OutputAlarmType {

    @XmlElement(name = "TechRegId", required = true, namespace = "http://avaya.com/v4/techregistration")
    protected String techRegId;
    @XmlElement(name = "OnBoardingOP", required = true, namespace = "http://avaya.com/v4/techregistration")
    protected String onBoardingOp;
    @XmlElement(name = "SEid", required = true, namespace = "http://avaya.com/v4/techregistration")
    protected String seid;
    @XmlElement(name = "AccessType", required = true, namespace = "http://avaya.com/v4/techregistration")
    protected String accessType;
    @XmlElement(name = "ActivityLog", required = true, namespace = "http://avaya.com/v4/techregistration")
    protected String activityLog;
    @XmlElement(name = "ReturnCode", required = true, namespace = "http://avaya.com/v4/techregistration")
    protected String returnCode;
    @XmlElement(name = "Description", required = true, namespace = "http://avaya.com/v4/techregistration")
    protected String description;
    @XmlElement(name = "Parameters", namespace = "http://avaya.com/v4/techregistration")
    protected List<KeyValueListType> keyValueList;
    
	public String getTechRegId() {
		return techRegId;
	}
	
	public void setTechRegId(String techRegId) {
		this.techRegId = techRegId;
	}
	
	public String getSeid() {
		return seid;
	}
	
	public String getOnBoardingOp() {
		return onBoardingOp;
	}
	
	public void setOnBoardingOp(String onBoardingOp) {
		this.onBoardingOp = onBoardingOp;
	}
	
	public void setSeid(String seid) {
		this.seid = seid;
	}
	
	public String getAccessType() {
		return accessType;
	}
	
	public void setAccessType(String accessType) {
		this.accessType = accessType;
	}
	
	public String getActivityLog() {
		return activityLog;
	}
	
	public void setActivityLog(String activityLog) {
		this.activityLog = activityLog;
	}
	
	public String getReturnCode() {
		return returnCode;
	}
	
	public void setReturnCode(String returnCode) {
		this.returnCode = returnCode;
	}
	
	public String getDescription() {
		return description;
	}
	
	public void setDescription(String description) {
		this.description = description;
	}
	
	public List<KeyValueListType> getKeyValueList() {
		if (keyValueList == null) {
			keyValueList = new ArrayList<KeyValueListType>();
        }
		return keyValueList;
	}

	public void setKeyValueList(List<KeyValueListType> keyValueList) {
		this.keyValueList = keyValueList;
	}
    
}
