//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.27 at 11:51:31 AM EDT 
//


package com.avaya.grt.jms.fmw.xml.equipmentMove.jms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RespheaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RespheaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RegId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>IBaseCreateRespHeader
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EquipmentMoveResponse", propOrder = {   
	"systemId",
    "transactionId",
    "fromSoldToId",
    "toSoldToId",
    "returnCode",
    "errorDesc",
    "routingInfo"
    
})
public class EquipmentMoveResponse {

	@XmlElement(name = "SystemId", namespace = "http://avaya.com/v4/equipmentmove")
    protected String systemId;
	
    @XmlElement(name = "TransactionId", namespace = "http://avaya.com/v4/equipmentmove")
    protected String transactionId;
    
    @XmlElement(name = "FromSoldtoId", namespace = "http://avaya.com/v4/equipmentmove")
    protected String fromSoldToId;
    
    @XmlElement(name = "ToSoldtoId", namespace = "http://avaya.com/v4/equipmentmove")
    protected String toSoldToId;
    
    @XmlElement(name = "ReturnCode", namespace = "http://avaya.com/v4/equipmentmove")
    protected String returnCode;
    
    @XmlElement(name = "ErrorDesc", namespace = "http://avaya.com/v4/equipmentmove")
    protected String errorDesc;
    
    @XmlElement(name = "RoutingInfo", namespace = "http://avaya.com/v4/equipmentmove")
    protected String routingInfo;

	public String getRoutingInfo() {
		return routingInfo;
	}

	public void setRoutingInfo(String routingInfo) {
		this.routingInfo = routingInfo;
	}

	public String getSystemId() {
		return systemId;
	}

	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}

	public String getTransactionId() {
		return transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getFromSoldToId() {
		return fromSoldToId;
	}

	public void setFromSoldToId(String fromSoldToId) {
		this.fromSoldToId = fromSoldToId;
	}

	public String getToSoldToId() {
		return toSoldToId;
	}

	public void setToSoldToId(String toSoldToId) {
		this.toSoldToId = toSoldToId;
	}

	public String getReturnCode() {
		return returnCode;
	}

	public void setReturnCode(String returnCode) {
		this.returnCode = returnCode;
	}

	public String getErrorDesc() {
		return errorDesc;
	}

	public void setErrorDesc(String errorDesc) {
		this.errorDesc = errorDesc;
	}

	

}
