//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 11:47:56 AM IST 
//


package com.avaya.grt.jms.avaya.v2.techregistration;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.avaya.v2.techregistration package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TechRegRequest_QNAME = new QName("http://avaya.com/v2/techregistration", "TechRegRequest");
    private final static QName _TechRegResponse_QNAME = new QName("http://avaya.com/v2/techregistration", "TechRegResponse");
    private final static QName _TechRegResultRequest_QNAME = new QName("http://avaya.com/v2/techregistration", "TechRegResultRequest");
    private final static QName _TechRegResultResponse_QNAME = new QName("http://avaya.com/v2/techregistration", "TechRegResultResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.avaya.v2.techregistration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegResultType }
     * 
     */
    public RegResultType createRegResultType() {
        return new RegResultType();
    }

    /**
     * Create an instance of {@link NewSEType }
     * 
     */
    public NewSEType createNewSEType() {
        return new NewSEType();
    }

    /**
     * Create an instance of {@link ResponseType }
     * 
     */
    public ResponseType createResponseType() {
        return new ResponseType();
    }

    /**
     * Create an instance of {@link TechRegRespType }
     * 
     */
    public TechRegRespType createTechRegRespType() {
        return new TechRegRespType();
    }

    /**
     * Create an instance of {@link TechRegRequestType }
     * 
     */
    public TechRegRequestType createTechRegRequestType() {
        return new TechRegRequestType();
    }

    /**
     * Create an instance of {@link TRResponseResultType }
     * 
     */
    public TRResponseResultType createTRResponseResultType() {
        return new TRResponseResultType();
    }

    /**
     * Create an instance of {@link TechRegDataType }
     * 
     */
    public TechRegDataType createTechRegDataType() {
        return new TechRegDataType();
    }

    /**
     * Create an instance of {@link TechRegAcknowledgementType }
     * 
     */
    public TechRegAcknowledgementType createTechRegAcknowledgementType() {
        return new TechRegAcknowledgementType();
    }

    /**
     * Create an instance of {@link OutputType }
     * 
     */
    public OutputType createOutputType() {
        return new OutputType();
    }

    /**
     * Create an instance of {@link TechRegResponseListType }
     * 
     */
    public TechRegResponseListType createTechRegResponseListType() {
        return new TechRegResponseListType();
    }

    /**
     * Create an instance of {@link RegResultType.Warning }
     * 
     */
    public RegResultType.Warning createRegResultTypeWarning() {
        return new RegResultType.Warning();
    }

    /**
     * Create an instance of {@link NewSEType.NewSEID }
     * 
     */
    public NewSEType.NewSEID createNewSETypeNewSEID() {
        return new NewSEType.NewSEID();
    }

    /**
     * Create an instance of {@link NewSEType.FailedSEID }
     * 
     */
    public NewSEType.FailedSEID createNewSETypeFailedSEID() {
        return new NewSEType.FailedSEID();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TechRegRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://avaya.com/v2/techregistration", name = "TechRegRequest")
    public JAXBElement<TechRegRequestType> createTechRegRequest(TechRegRequestType value) {
        return new JAXBElement<TechRegRequestType>(_TechRegRequest_QNAME, TechRegRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TechRegRespType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://avaya.com/v2/techregistration", name = "TechRegResponse")
    public JAXBElement<TechRegRespType> createTechRegResponse(TechRegRespType value) {
        return new JAXBElement<TechRegRespType>(_TechRegResponse_QNAME, TechRegRespType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://avaya.com/v2/techregistration", name = "TechRegResultRequest")
    public JAXBElement<ResponseType> createTechRegResultRequest(ResponseType value) {
        return new JAXBElement<ResponseType>(_TechRegResultRequest_QNAME, ResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRResponseResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://avaya.com/v2/techregistration", name = "TechRegResultResponse")
    public JAXBElement<TRResponseResultType> createTechRegResultResponse(TRResponseResultType value) {
        return new JAXBElement<TRResponseResultType>(_TechRegResultResponse_QNAME, TRResponseResultType.class, null, value);
    }

}
