//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 11:47:56 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://avaya.com/v2/techregistration", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.avaya.grt.jms.avaya.v2.techregistration;
