//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 11:47:56 AM IST 
//


package com.avaya.grt.jms.avaya.v2.techregistration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RegResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Artid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Warning" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="WarningCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="WarningDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ReturnCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReturnSubCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegResultType", propOrder = {
    "artid",
    "warning",
    "returnCode",
    "returnSubCode",
    "description"
})
public class RegResultType {

    @XmlElement(name = "Artid", required = true)
    protected String artid;
    @XmlElement(name = "Warning")
    protected RegResultType.Warning warning;
    @XmlElement(name = "ReturnCode", required = true)
    protected String returnCode;
    @XmlElement(name = "ReturnSubCode", required = true)
    protected String returnSubCode;
    @XmlElement(name = "Description", required = true)
    protected String description;

    /**
     * Gets the value of the artid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtid() {
        return artid;
    }

    /**
     * Sets the value of the artid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtid(String value) {
        this.artid = value;
    }

    /**
     * Gets the value of the warning property.
     * 
     * @return
     *     possible object is
     *     {@link RegResultType.Warning }
     *     
     */
    public RegResultType.Warning getWarning() {
        return warning;
    }

    /**
     * Sets the value of the warning property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegResultType.Warning }
     *     
     */
    public void setWarning(RegResultType.Warning value) {
        this.warning = value;
    }

    /**
     * Gets the value of the returnCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * Sets the value of the returnCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnCode(String value) {
        this.returnCode = value;
    }

    /**
     * Gets the value of the returnSubCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnSubCode() {
        return returnSubCode;
    }

    /**
     * Sets the value of the returnSubCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnSubCode(String value) {
        this.returnSubCode = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="WarningCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="WarningDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "warningCode",
        "warningDescription"
    })
    public static class Warning {

        @XmlElement(name = "WarningCode")
        protected String warningCode;
        @XmlElement(name = "WarningDescription")
        protected String warningDescription;

        /**
         * Gets the value of the warningCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWarningCode() {
            return warningCode;
        }

        /**
         * Sets the value of the warningCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWarningCode(String value) {
            this.warningCode = value;
        }

        /**
         * Gets the value of the warningDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWarningDescription() {
            return warningDescription;
        }

        /**
         * Sets the value of the warningDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWarningDescription(String value) {
            this.warningDescription = value;
        }

    }

}
