//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 11:47:56 AM IST 
//


package com.avaya.grt.jms.avaya.v2.techregistration;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TechRegDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TechRegDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TechRegId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TechRegDetail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Usrid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Optype">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="DU"/>
 *               &lt;enumeration value="DN"/>
 *               &lt;enumeration value="RN"/>
 *               &lt;enumeration value="PR"/>
 *               &lt;enumeration value="FN"/>
 *               &lt;enumeration value="ON"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SummaryEquipmentNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EquipmentNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GroupId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Mcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Scode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Relno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SPRel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Inads" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Ipadd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Sid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Mid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Aorig">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Rndpwd">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value="D"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Prvip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Vpmsldn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Foption">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="on"/>
 *               &lt;enumeration value="off"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IsDOCR">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="on"/>
 *               &lt;enumeration value="off"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Afid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Ossno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Svrname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Nickname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Hwsvr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MainSEID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FailedSEID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Custipaddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Almid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TechRegDataType", propOrder = {
    "techRegId",
    "techRegDetail",
    "usrid",
    "fl",
    "optype",
    "summaryEquipmentNumber",
    "equipmentNumber",
    "groupId",
    "mcode",
    "scode",
    "relno",
    "spRel",
    "inads",
    "ipadd",
    "sid",
    "mid",
    "aorig",
    "rndpwd",
    "prvip",
    "vpmsldn",
    "foption",
    "isDOCR",
    "afid",
    "ossno",
    "svrname",
    "nickname",
    "hwsvr",
    "mainSEID",
    "failedSEID",
    "custipaddress",
    "almid",
    "keyValueList"
})
public class TechRegDataType {

    @XmlElement(name = "TechRegId", required = true)
    protected String techRegId;
    @XmlElement(name = "TechRegDetail", required = true)
    protected String techRegDetail;
    @XmlElement(name = "Usrid", required = true)
    protected String usrid;
    @XmlElement(name = "FL", required = true)
    protected String fl;
    @XmlElement(name = "Optype", required = true)
    protected String optype;
    @XmlElement(name = "SummaryEquipmentNumber", required = true)
    protected String summaryEquipmentNumber;
    @XmlElement(name = "EquipmentNumber")
    protected String equipmentNumber;
    @XmlElement(name = "GroupId", required = true)
    protected String groupId;
    @XmlElement(name = "Mcode", required = true)
    protected String mcode;
    @XmlElement(name = "Scode", required = true)
    protected String scode;
    @XmlElement(name = "Relno", required = true)
    protected String relno;
    @XmlElement(name = "SPRel")
    protected String spRel;
    @XmlElement(name = "Inads", required = true)
    protected String inads;
    @XmlElement(name = "Ipadd", required = true)
    protected String ipadd;
    @XmlElement(name = "Sid", required = true)
    protected String sid;
    @XmlElement(name = "Mid", required = true)
    protected String mid;
    @XmlElement(name = "Aorig", required = true)
    protected String aorig;
    @XmlElement(name = "Rndpwd", required = true)
    protected String rndpwd;
    @XmlElement(name = "Prvip", required = true)
    protected String prvip;
    @XmlElement(name = "Vpmsldn", required = true)
    protected String vpmsldn;
    @XmlElement(name = "Foption", required = true)
    protected String foption;
    @XmlElement(name = "IsDOCR", required = true)
    protected String isDOCR;
    @XmlElement(name = "Afid", required = true)
    protected String afid;
    @XmlElement(name = "Ossno", required = true)
    protected String ossno;
    @XmlElement(name = "Svrname", required = true)
    protected String svrname;
    @XmlElement(name = "Nickname", required = true)
    protected String nickname;
    @XmlElement(name = "Hwsvr", required = true)
    protected String hwsvr;
    @XmlElement(name = "MainSEID", required = true)
    protected String mainSEID;
    @XmlElement(name = "FailedSEID", required = true)
    protected String failedSEID;
    @XmlElement(name = "Custipaddress", required = true)
    protected String custipaddress;
    @XmlElement(name = "Almid", required = true)
    protected String almid;
    @XmlElement(name = "Parameters")
    protected List<KeyValueListType> keyValueList;

    /**
     * Gets the value of the techRegId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechRegId() {
        return techRegId;
    }

    /**
     * Sets the value of the techRegId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechRegId(String value) {
        this.techRegId = value;
    }

    /**
     * Gets the value of the techRegDetail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechRegDetail() {
        return techRegDetail;
    }

    /**
     * Sets the value of the techRegDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechRegDetail(String value) {
        this.techRegDetail = value;
    }

    /**
     * Gets the value of the usrid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsrid() {
        return usrid;
    }

    /**
     * Sets the value of the usrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsrid(String value) {
        this.usrid = value;
    }

    /**
     * Gets the value of the fl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFL() {
        return fl;
    }

    /**
     * Sets the value of the fl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFL(String value) {
        this.fl = value;
    }

    /**
     * Gets the value of the optype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptype() {
        return optype;
    }

    /**
     * Sets the value of the optype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptype(String value) {
        this.optype = value;
    }

    /**
     * Gets the value of the summaryEquipmentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummaryEquipmentNumber() {
        return summaryEquipmentNumber;
    }

    /**
     * Sets the value of the summaryEquipmentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummaryEquipmentNumber(String value) {
        this.summaryEquipmentNumber = value;
    }

    /**
     * Gets the value of the equipmentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipmentNumber() {
        return equipmentNumber;
    }

    /**
     * Sets the value of the equipmentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipmentNumber(String value) {
        this.equipmentNumber = value;
    }

    /**
     * Gets the value of the groupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupId(String value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the mcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMcode() {
        return mcode;
    }

    /**
     * Sets the value of the mcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMcode(String value) {
        this.mcode = value;
    }

    /**
     * Gets the value of the scode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScode() {
        return scode;
    }

    /**
     * Sets the value of the scode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScode(String value) {
        this.scode = value;
    }

    /**
     * Gets the value of the relno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelno() {
        return relno;
    }

    /**
     * Sets the value of the relno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelno(String value) {
        this.relno = value;
    }

    /**
     * Gets the value of the spRel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPRel() {
        return spRel;
    }

    /**
     * Sets the value of the spRel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPRel(String value) {
        this.spRel = value;
    }

    /**
     * Gets the value of the inads property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInads() {
        return inads;
    }

    /**
     * Sets the value of the inads property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInads(String value) {
        this.inads = value;
    }

    /**
     * Gets the value of the ipadd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpadd() {
        return ipadd;
    }

    /**
     * Sets the value of the ipadd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpadd(String value) {
        this.ipadd = value;
    }

    /**
     * Gets the value of the sid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSid() {
        return sid;
    }

    /**
     * Sets the value of the sid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSid(String value) {
        this.sid = value;
    }

    /**
     * Gets the value of the mid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMid() {
        return mid;
    }

    /**
     * Sets the value of the mid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMid(String value) {
        this.mid = value;
    }

    /**
     * Gets the value of the aorig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAorig() {
        return aorig;
    }

    /**
     * Sets the value of the aorig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAorig(String value) {
        this.aorig = value;
    }

    /**
     * Gets the value of the rndpwd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRndpwd() {
        return rndpwd;
    }

    /**
     * Sets the value of the rndpwd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRndpwd(String value) {
        this.rndpwd = value;
    }

    /**
     * Gets the value of the prvip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrvip() {
        return prvip;
    }

    /**
     * Sets the value of the prvip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrvip(String value) {
        this.prvip = value;
    }

    /**
     * Gets the value of the vpmsldn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVpmsldn() {
        return vpmsldn;
    }

    /**
     * Sets the value of the vpmsldn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVpmsldn(String value) {
        this.vpmsldn = value;
    }

    /**
     * Gets the value of the foption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFoption() {
        return foption;
    }

    /**
     * Sets the value of the foption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFoption(String value) {
        this.foption = value;
    }

    /**
     * Gets the value of the isDOCR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsDOCR() {
        return isDOCR;
    }

    /**
     * Sets the value of the isDOCR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsDOCR(String value) {
        this.isDOCR = value;
    }

    /**
     * Gets the value of the afid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAfid() {
        return afid;
    }

    /**
     * Sets the value of the afid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAfid(String value) {
        this.afid = value;
    }

    /**
     * Gets the value of the ossno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOssno() {
        return ossno;
    }

    /**
     * Sets the value of the ossno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOssno(String value) {
        this.ossno = value;
    }

    /**
     * Gets the value of the svrname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSvrname() {
        return svrname;
    }

    /**
     * Sets the value of the svrname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSvrname(String value) {
        this.svrname = value;
    }

    /**
     * Gets the value of the nickname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * Sets the value of the nickname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNickname(String value) {
        this.nickname = value;
    }

    /**
     * Gets the value of the hwsvr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHwsvr() {
        return hwsvr;
    }

    /**
     * Sets the value of the hwsvr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHwsvr(String value) {
        this.hwsvr = value;
    }

    /**
     * Gets the value of the mainSEID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainSEID() {
        return mainSEID;
    }

    /**
     * Sets the value of the mainSEID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainSEID(String value) {
        this.mainSEID = value;
    }

    /**
     * Gets the value of the failedSEID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFailedSEID() {
        return failedSEID;
    }

    /**
     * Sets the value of the failedSEID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFailedSEID(String value) {
        this.failedSEID = value;
    }

    /**
     * Gets the value of the custipaddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustipaddress() {
        return custipaddress;
    }

    /**
     * Sets the value of the custipaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustipaddress(String value) {
        this.custipaddress = value;
    }

    /**
     * Gets the value of the almid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlmid() {
        return almid;
    }

    /**
     * Sets the value of the almid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlmid(String value) {
        this.almid = value;
    }

	public List<KeyValueListType> getKeyValueList() {
		if (keyValueList == null) {
			keyValueList = new ArrayList<KeyValueListType>();
        }
		return keyValueList;
	}

	public void setKeyValueList(List<KeyValueListType> keyValueList) {
		this.keyValueList = keyValueList;
	}

}
