//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.08 at 12:50:13 PM EDT 
//


package com.avaya.grt.jms.avaya.v2.techregistration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for TechRegRespType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TechRegRespType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="artid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="grtid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="artsr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TechRegRespType", propOrder = {
    "artid",
    "grtid",
    "artsr",
    "code",
    "description"
})
public class TechRegRespType {

    @XmlElement(name = "Artid")
    protected String artid;
    @XmlElement(name = "Grtid")
    protected String grtid;
    @XmlElement(name = "Artsr")
    protected String artsr;
    @XmlElement(name = "Code")
    protected String code;
    @XmlElement(name = "Description")
    protected String description;

    /**
     * Gets the value of the artid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtid() {
        return artid;
    }

    /**
     * Sets the value of the artid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtid(String value) {
        this.artid = value;
    }

    /**
     * Gets the value of the grtid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrtid() {
        return grtid;
    }

    /**
     * Sets the value of the grtid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrtid(String value) {
        this.grtid = value;
    }

    /**
     * Gets the value of the artsr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtsr() {
        return artsr;
    }

    /**
     * Sets the value of the artsr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtsr(String value) {
        this.artsr = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
