//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 11:47:56 AM IST 
//


package com.avaya.grt.jms.avaya.v2.techregistration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TechRegAcknowledgementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TechRegAcknowledgementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Artid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TechRegId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TechRegDetail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SubCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TechRegAcknowledgementType", propOrder = {
    "artid",
    "techRegId",
    "techRegDetail",
    "code",
    "subCode",
    "description"
})
public class TechRegAcknowledgementType {

    @XmlElement(name = "Artid", required = true)
    protected String artid;
    @XmlElement(name = "TechRegId", required = true)
    protected String techRegId;
    @XmlElement(name = "TechRegDetail", required = true)
    protected String techRegDetail;
    @XmlElement(name = "Code", required = true)
    protected String code;
    @XmlElement(name = "SubCode", required = true)
    protected String subCode;
    @XmlElement(name = "Description")
    protected String description;

    /**
     * Gets the value of the artid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtid() {
        return artid;
    }

    /**
     * Sets the value of the artid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtid(String value) {
        this.artid = value;
    }

    /**
     * Gets the value of the techRegId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechRegId() {
        return techRegId;
    }

    /**
     * Sets the value of the techRegId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechRegId(String value) {
        this.techRegId = value;
    }

    /**
     * Gets the value of the techRegDetail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechRegDetail() {
        return techRegDetail;
    }

    /**
     * Sets the value of the techRegDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechRegDetail(String value) {
        this.techRegDetail = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the subCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubCode() {
        return subCode;
    }

    /**
     * Sets the value of the subCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubCode(String value) {
        this.subCode = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
