//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.08 at 12:50:13 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://avaya.com/v4/techregistration")
package com.avaya.grt.jms.avaya.v4.techregistration;
