//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.28 at 12:54:43 PM CDT 
//


package com.avaya.grt.service.iposs.ipoInventory10;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.grt.ipoInventory10 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.grt.ipoInventory10
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link Response.Data }
     * 
     */
    public Response.Data createResponseData() {
        return new Response.Data();
    }

    /**
     * Create an instance of {@link Response.Data.Inventory }
     * 
     */
    public Response.Data.Inventory createResponseDataInventory() {
        return new Response.Data.Inventory();
    }

    /**
     * Create an instance of {@link Response.Data.Inventory.IdentityCertificates }
     * 
     */
    public Response.Data.Inventory.IdentityCertificates createResponseDataInventoryIdentityCertificates() {
        return new Response.Data.Inventory.IdentityCertificates();
    }

    /**
     * Create an instance of {@link Response.Data.Inventory.Licenses }
     * 
     */
    public Response.Data.Inventory.Licenses createResponseDataInventoryLicenses() {
        return new Response.Data.Inventory.Licenses();
    }

    /**
     * Create an instance of {@link Response.Data.Inventory.Software }
     * 
     */
    public Response.Data.Inventory.Software createResponseDataInventorySoftware() {
        return new Response.Data.Inventory.Software();
    }

    /**
     * Create an instance of {@link Response.Data.Inventory.Hardware }
     * 
     */
    public Response.Data.Inventory.Hardware createResponseDataInventoryHardware() {
        return new Response.Data.Inventory.Hardware();
    }

    /**
     * Create an instance of {@link Response.Data.Inventory.Hardware.Modules }
     * 
     */
    public Response.Data.Inventory.Hardware.Modules createResponseDataInventoryHardwareModules() {
        return new Response.Data.Inventory.Hardware.Modules();
    }

    /**
     * Create an instance of {@link Response.Data.Inventory.Hardware.Units }
     * 
     */
    public Response.Data.Inventory.Hardware.Units createResponseDataInventoryHardwareUnits() {
        return new Response.Data.Inventory.Hardware.Units();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link Response.Data.Inventory.SystemConfigSummary }
     * 
     */
    public Response.Data.Inventory.SystemConfigSummary createResponseDataInventorySystemConfigSummary() {
        return new Response.Data.Inventory.SystemConfigSummary();
    }

    /**
     * Create an instance of {@link Response.Data.Inventory.IdentityCertificates.IdentityCertificate }
     * 
     */
    public Response.Data.Inventory.IdentityCertificates.IdentityCertificate createResponseDataInventoryIdentityCertificatesIdentityCertificate() {
        return new Response.Data.Inventory.IdentityCertificates.IdentityCertificate();
    }

    /**
     * Create an instance of {@link Response.Data.Inventory.Licenses.License }
     * 
     */
    public Response.Data.Inventory.Licenses.License createResponseDataInventoryLicensesLicense() {
        return new Response.Data.Inventory.Licenses.License();
    }

    /**
     * Create an instance of {@link Response.Data.Inventory.Software.Component }
     * 
     */
    public Response.Data.Inventory.Software.Component createResponseDataInventorySoftwareComponent() {
        return new Response.Data.Inventory.Software.Component();
    }

    /**
     * Create an instance of {@link Response.Data.Inventory.Hardware.SDCard }
     * 
     */
    public Response.Data.Inventory.Hardware.SDCard createResponseDataInventoryHardwareSDCard() {
        return new Response.Data.Inventory.Hardware.SDCard();
    }

    /**
     * Create an instance of {@link Response.Data.Inventory.Hardware.Modules.Module }
     * 
     */
    public Response.Data.Inventory.Hardware.Modules.Module createResponseDataInventoryHardwareModulesModule() {
        return new Response.Data.Inventory.Hardware.Modules.Module();
    }

    /**
     * Create an instance of {@link Response.Data.Inventory.Hardware.Units.Unit }
     * 
     */
    public Response.Data.Inventory.Hardware.Units.Unit createResponseDataInventoryHardwareUnitsUnit() {
        return new Response.Data.Inventory.Hardware.Units.Unit();
    }

}
