//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.27 at 11:51:31 AM EDT 
//


package com.avaya.grt.jms.fmw.xml.filePoller.jms;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import com.avaya.grt.jms.fmw.xml.filePoller.jms.HeaderType;
import com.avaya.grt.jms.fmw.xml.filePoller.jms.IBaseCreateFailMessageType;
import com.avaya.grt.jms.fmw.xml.filePoller.jms.IBaseCreateRequestType;
import com.avaya.grt.jms.fmw.xml.filePoller.jms.IBaseCreateRespType;
import com.avaya.grt.jms.fmw.xml.filePoller.jms.IBaseCreateResponseType;
import com.avaya.grt.jms.fmw.xml.filePoller.jms.IBaseDataType;
import com.avaya.grt.jms.fmw.xml.filePoller.jms.IBaseRespDataType;
import com.avaya.grt.jms.fmw.xml.filePoller.jms.ObjectFactory;
import com.avaya.grt.jms.fmw.xml.filePoller.jms.RespheaderType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ibaseCreation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IBaseResponse_QNAME = new QName("http://avaya.com/v1/installbase", "iBaseResponse");
    private final static QName _IBaseCreateFailMessage_QNAME = new QName("http://avaya.com/v1/installbase", "iBaseCreateFailMessage");
    private final static QName _IBaseCreateResponse_QNAME = new QName("http://avaya.com/v1/installbase", "iBaseCreateResponse");
    private final static QName _IBaseCreateRequest_QNAME = new QName("http://avaya.com/v1/installbase", "iBaseCreateRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ibaseCreation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link IBaseCreateRequestType }
     * 
     */
    public IBaseCreateRequestType createIBaseCreateRequestType() {
        return new IBaseCreateRequestType();
    }

    /**
     * Create an instance of {@link IBaseCreateFailMessageType }
     * 
     */
    public IBaseCreateFailMessageType createIBaseCreateFailMessageType() {
        return new IBaseCreateFailMessageType();
    }

    /**
     * Create an instance of {@link IBaseCreateResponseType }
     * 
     */
    public IBaseCreateResponseType createIBaseCreateResponseType() {
        return new IBaseCreateResponseType();
    }

    /**
     * Create an instance of {@link IBaseRespDataType }
     * 
     */
    public IBaseRespDataType createIBaseRespDataType() {
        return new IBaseRespDataType();
    }

    /**
     * Create an instance of {@link IBaseCreateRespType }
     * 
     */
    public IBaseCreateRespType createIBaseCreateRespType() {
        return new IBaseCreateRespType();
    }

    /**
     * Create an instance of {@link IBaseDataType }
     * 
     */
    public IBaseDataType createIBaseDataType() {
        return new IBaseDataType();
    }

    /**
     * Create an instance of {@link RespheaderType }
     * 
     */
    public RespheaderType createRespheaderType() {
        return new RespheaderType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IBaseCreateRespType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://avaya.com/v1/installbase", name = "iBaseResponse")
    public JAXBElement<IBaseCreateRespType> createIBaseResponse(IBaseCreateRespType value) {
        return new JAXBElement<IBaseCreateRespType>(_IBaseResponse_QNAME, IBaseCreateRespType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IBaseCreateFailMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://avaya.com/v1/installbase", name = "iBaseCreateFailMessage")
    public JAXBElement<IBaseCreateFailMessageType> createIBaseCreateFailMessage(IBaseCreateFailMessageType value) {
        return new JAXBElement<IBaseCreateFailMessageType>(_IBaseCreateFailMessage_QNAME, IBaseCreateFailMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IBaseCreateResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://avaya.com/v1/installbase", name = "iBaseCreateResponse")
    public JAXBElement<IBaseCreateResponseType> createIBaseCreateResponse(IBaseCreateResponseType value) {
        return new JAXBElement<IBaseCreateResponseType>(_IBaseCreateResponse_QNAME, IBaseCreateResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IBaseCreateRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://avaya.com/v1/installbase", name = "iBaseCreateRequest")
    public JAXBElement<IBaseCreateRequestType> createIBaseCreateRequest(IBaseCreateRequestType value) {
        return new JAXBElement<IBaseCreateRequestType>(_IBaseCreateRequest_QNAME, IBaseCreateRequestType.class, null, value);
    }

}
